language: node_js
node_js:
  - node
services: mongodb
before_script:
    - cp config/database-local.dist.js config/database-local.js
    - cp config/database-local.dist.js test/database-local.js
    - cp config/mail-local.dist.js config/mail-local.js
    - mongo qwertykey --eval 'db.createUser({user:"user",pwd:"password",roles:["readWrite"]});'
